spring.application.name=backend


spring.datasource.url=jdbc:postgresql://localhost:5432/tripnest_db
spring.datasource.username=postgres
spring.datasource.password=your_postgres_password 
# // change to postgres pw

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=tripnest-secret-key-change-this-later-please-use-a-long-random-secret